# Generated by Django 5.1.2 on 2024-11-01 04:39

import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Subscribers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', tinymce.models.HTMLField()),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('content_type', models.CharField(choices=[('MVP', 'MVP'), ('skills', 'Skills'), ('startup', 'Startup Idea')], default='article', max_length=20)),
                ('author', models.CharField(default='Reanstartup', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('excerpt', models.TextField(blank=True, max_length=500)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('likes_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
